src/Entity/Bestellung.php
<?php

namespace App\Entity;

use App\Repository\BestellungRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BestellungRepository::class)]
class Bestellung
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tisch = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Bestellnummer = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $preis = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTisch(): ?string
    {
        return $this->tisch;
    }

    public function setTisch(?string $tisch): static
    {
        $this->tisch = $tisch;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPreis(): ?string
    {
        return $this->preis;
    }

    public function setPreis(?string $preis): static
    {
        $this->preis = $preis;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getBestellnummer(): ?string
    {
        return $this->Bestellnummer;
    }

    public function setBestellnummer(?string $Bestellnummer): static
    {
        $this->Bestellnummer = $Bestellnummer;

        return $this;
    }
}

src/Controller/BestellungController.php
<?php

namespace App\Controller;

use App\Entity\Bestellung;
use App\Entity\Gericht;
use App\Repository\BestellungRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BestellungController extends AbstractController
{
    #[Route('/bestellung', name: 'bestellung')]
    public function index(BestellungRepository $bestellungRepository): Response
    {
        $bestellungen = $bestellungRepository->findBy([
            "tisch" => "Tisch1",
        ]);
        
        return $this->render('bestellung/index.html.twig', [
            'bestellungen' => $bestellungen,
        ]);
    }

    #[Route('/bestellen/{id}', name: 'bestellen')]
    public function bestellen(Gericht $gericht, EntityManagerInterface $manager): Response
    {
        $bestellung = (new Bestellung)
            ->setTisch("Tisch1")
            ->setName($gericht->getName())
            ->setBestellnummer($gericht->getId())
            ->setPreis($gericht->getPreis())
            ->setStatus("offen");

        $manager->persist($bestellung);
        $manager->flush();

        $this->addFlash("bestell", $bestellung->getName() . " wurde zu Bestellung hinzugefügt.");

        return $this->redirect($this->generateUrl('menu'));
    }

    #[Route('/status/{id},{status}', name: 'status')]
    public function status($id, $status, EntityManagerInterface $manager): Response
    {
        $bestellung = $manager->getRepository(Bestellung::class)->find($id);
        $bestellung->setStatus($status);
        $manager->flush();

        return $this->redirect($this->generateUrl("bestellung"));
    }

    #[Route('/löschen/{id}', name: 'löschen')]
    public function löschen($id, BestellungRepository $bestellungRepository, EntityManagerInterface $manager): Response
    {
        $bestellung = $bestellungRepository->find($id);
        $manager->remove($bestellung);
        $manager->flush();

        $this->addFlash("erfolg", "bestellung wurde erfolgreich entfernt");

        return $this->redirect($this->generateUrl('bestellung'));
    }
}

templates/bestellung/index.html.twig
{% extends 'base.html.twig' %}

{% set summe = 0 %}

{% block body %}
	<h2>Ihre Bestellung</h2>
	<br>
	<table class="table table-striped">
		<thead>
			<tr>
				<td>Bestellnummer</td>
				{% if not is_granted("IS_AUTHENTICATED_FULLY") %}
					<td>Tisch</td>
				{% endif %}
				<td>Name</td>
				<td>Preis</td>
				<td>Status</td>
				{% if is_granted("IS_AUTHENTICATED_FULLY") %}
					<td>Status ändern</td>
				{% endif %}
				<td>Löschen</td>

			</tr>
		</thead>
		<tbody>
			{% for bestellung in bestellungen %}
				{% if bestellung.status != "archiv" %}
					{% set summe = summe + bestellung.preis %}
					<tr>
						<td>{{bestellung.bestellnummer}}</td>
						{% if not is_granted("IS_AUTHENTICATED_FULLY") %}
							<td>{{bestellung.tisch}}</td>
						{% endif %}
						<td>{{bestellung.name}}</td>
						<td>{{bestellung.preis}}</td>
						<td>{{bestellung.status}}</td>
						{% if is_granted("IS_AUTHENTICATED_FULLY") %}
							<td>
								<div class="dropdown">
									<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
										{{bestellung.status}}
									</button>
									<ul class="dropdown-menu">
										<li>
											<a class="dropdown-item" href="{{path('status', {id: bestellung.id, status: 'offen'})}}">Offen</a>
										</li>
										<li>
											<a class="dropdown-item" href="{{path('status', {id: bestellung.id, status: 'fertig'})}}">Fertig</a>
										</li>
										<li>
											<a class="dropdown-item" href="{{path('status', {id: bestellung.id, status: 'archiv'})}}">Archiv</a>
										</li>
									</ul>
								</div>
							</td>
						{% endif %}
						{% if bestellung.status == "offen" %}
							<td>
								<a href="{{path('löschen', {id: bestellung.id})}}">X</a>
							</td>
						{% endif %}
					</tr>
					<tr>
					{% endif %}
				{% endfor %}
				<tr>
					<td>Summe.:
						{{summe}}€</td>
				</tr>
			</tbody>
		</tbody>

	</table>
{% endblock %}